*Nonparametric Tests: Related Samples.
NPTESTS
  /RELATED TEST(eff_R eff_S)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_R eff_F)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_S eff_F)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_cmdline eff_nametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_cmdline eff_ntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_nametbl eff_ntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rcmdline eff_Rnametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rcmdline eff_Rntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rnametbl eff_Rntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Scmdline eff_Snametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Scmdline eff_Sntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Snametbl eff_Sntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Fcmdline eff_Fnametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Fcmdline eff_Fntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Fnametbl eff_Fntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rcmdline eff_Scmdline)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rcmdline eff_Fcmdline)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Scmdline eff_Fcmdline)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rnametbl eff_Snametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rnametbl eff_Fnametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Snametbl eff_Fnametbl)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rntree eff_Sntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Rntree eff_Fntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.

NPTESTS
  /RELATED TEST(eff_Sntree eff_Fntree)
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.
