* Encoding: UTF-8.

DATASET ACTIVATE ConjuntoDatos2.
NPAR TESTS
  /WILCOXON=ProdTDD ProdBSK_S ProdITL_BSK_S ProdTDD_BSK_S ProdITL_BSK_S ProdITL_MR_NS
  WITH ProdITL ProdMR_NS ProdITL_MR_NS ProdTDD_MR_NS ProdTDD_BSK_S ProdTDD_MR_NS (PAIRED)
  /MISSING ANALYSIS.

  NPAR TESTS
  /WILCOXON=ProdITL_BSK_S ProdITL_MR_NS WITH ProdTDD_BSK_S ProdTDD_MR_NS (PAIRED)
  /MISSING ANALYSIS.

