* Encoding: UTF-8.

NPAR TESTS
  /WILCOXON=ProdTLD Prod_BSK_S ProdTLD_BSK_S ProdTDD_BSK_S ProdTLD_BSK_S ProdTLD_MR_S
    WITH ProdTDD ProdMR_S ProdTLD_MR_S ProdTDD_MR_S ProdTDD_BSK_S ProdTDD_MR_S (PAIRED)
  /MISSING ANALYSIS.

DATASET ACTIVATE ConjuntoDatos10.
NPAR TESTS
  /WILCOXON=ProdTLD_BSK_S ProdTLD_MR_S WITH ProdTDD_BSK_S ProdTDD_MR_S (PAIRED)
  /MISSING ANALYSIS.
