* Encoding: UTF-8.

DATASET ACTIVATE ConjuntoDatos1.
GLM ProdITL ProdTDD
  /WSFACTOR=Prod 2 Polynomial 
  /METHOD=SSTYPE(3)
  /EMMEANS=TABLES(OVERALL) 
  /EMMEANS=TABLES(Prod) COMPARE ADJ(BONFERRONI)
  /PRINT=DESCRIPTIVE ETASQ OPOWER 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Prod.
